import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MeeraLogo from "@/components/MeeraLogo";
import AppBar from "@/components/AppBar";
import { Typography } from "@mui/material";
import { footer } from "./constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eye Surgeon | Meerasight | New Delhi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <MeeraLogo />
          <AppBar />
        </header>
        {children}
        <footer>
          {footer.links.map((val, index) => <a key={index} href={val.link} target="_blank">{val.link || val.icon}</a>)}
          <Typography>
            {footer.text}
          </Typography>
        </footer>
      </body>
    </html>
  );
}
